if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    set(OS_NAME "linux" CACHE INTERNAL "OS base definition")
    set(OS_NAME_2 "Linux" CACHE INTERNAL "OS base definition")
    set(OS_NAME_3 "Linux" CACHE INTERNAL "OS base definition")
    add_definitions(-DLINUX -DOS_NAME="linux" -DOS_NAME_2="Linux" -DOS_NAME_3="Linux")
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    set(OS_NAME "windows" CACHE INTERNAL "OS base definition")
    set(OS_NAME_2 "Windows" CACHE INTERNAL "OS base definition")
    set(OS_NAME_3 "Windows" CACHE INTERNAL "OS base definition")
    add_definitions(-DWINDOWS)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    set(OS_NAME "macos" CACHE INTERNAL "OS base definition")
    set(OS_NAME_2 "macOS" CACHE INTERNAL "OS base definition")
    set(OS_NAME_3 "macOS" CACHE INTERNAL "OS base definition")
    add_definitions(-DMACOSX -DMACOS)
endif()
